### ISSUE TITLE
JSON problem in newest version

### ISSUE THREAD

**Issue by thirteenthorphan** [Spittie/4chan-x#14]
While JSON navigation is on i am unable to open navigation, board, and reply links in a new tab via middle click or cmd click (on mac). This is unfortunate as being able to open new pages in new tabs is handy.
The problem goes away when I disable JSON, but I like infinite scrolling and what not so it'd be ideal if I could get both.

**Comment by thirteenthorphan** [comment]
also this checkmark shows up at the top with JSON off
![ss 2014-02-25 at 1 34 03 am](https://f.cloud.github.com/assets/2565572/2256019/0bd1a4a0-9e00-11e3-9620-1322fcc88d84.png)

it's not really a problem it's just kind of disconcerting

**Comment by thirteenthorphan** [comment]
and apparently Thread Expansion only works with JSON on.

**Comment by Spittie** [comment]
Okay, first one should be fixed now. I'll release a new version later, in the meanwhile you can just try to reinstall it.

For the checkmark, I'm not sure why it's here. @zixaphir it has a purpose?

As for Thread Expansion working only with JSON on, it would probably be too much work to bring it back without it (It was there before loading the page with the api got introduced? I've never used it).

**Comment by zixaphir** [comment]
The checkmark is part of the Index Searching functionality. It's generally styled with CSS. I'm not sure why it's appearing, though, probably something to do with the style script?

**Comment by Spittie** [comment]
I guess so. It's here with AppChan too, as long as you disable "JSON navigation".
With "vanilla" 4chan X instead you see it only when you press on the [search] button.

**Comment by zixaphir** [comment]
wee~

I guess we could just hide it with CSS or just style it. Your call.

**Comment by Spittie** [comment]
I'd say hide, but I don't use it so I don't know what is it's usercase...
Maybe someone is using it as a "go" button instead of just pressing enter?
